namespace Nacara.Plugins.Internal

open System
open System.Diagnostics
open System.IO
open System.Security
open System.Text
open Nacara.Plugins

/// <summary>What a tool run left behind.</summary>
type SolidRun =
    {
        ExitCode: int
        Output: string
        TimedOut: bool
    }

/// <summary>The generated project the examples compile in.</summary>
/// <remarks>
/// It lives beside the site and is kept between builds, so Fable's cache, the restored packages
/// and <c>node_modules</c> are paid for once.
/// </remarks>
[<RequireQualifiedAccess>]
module SolidWorkspace =

    /// <summary>Write a file unless it already says this.</summary>
    /// <returns>True when it changed.</returns>
    let write (path: string) (content: string) =
        let unchanged = File.Exists path && File.ReadAllText path = content

        if not unchanged then
            Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
            File.WriteAllText(path, content)

        not unchanged

    let private escape (value: string) = SecurityElement.Escape value

    let projectFile (options: SolidExamplesOptions) (files: string list) =
        let compiles =
            files
            |> List.map (fun file -> $"""        <Compile Include="%s{escape file}" />""")
            |> String.concat "\n"

        $"""<Project Sdk="Microsoft.NET.Sdk">
    <!-- Generated by Partas.Nacara.Plugins.Solid. Edits are overwritten. -->
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <WarningsAsErrors>$(WarningsAsErrors);FS0025</WarningsAsErrors>
        <NoWarn>$(NoWarn);FS3370</NoWarn>
    </PropertyGroup>
    <ItemGroup>
%s{compiles}
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Partas.Solid" Version="%s{escape options.PartasVersion}" />
    </ItemGroup>
</Project>
"""

    let nugetConfig (options: SolidExamplesOptions) =
        let feeds =
            options.Feeds
            |> List.mapi (fun index feed -> $"""        <add key="feed%d{index}" value="%s{escape feed}" />""")
            |> String.concat "\n"

        $"""<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
%s{feeds}
    </packageSources>
</configuration>
"""

    let toolManifest (options: SolidExamplesOptions) =
        $"""{{
  "version": 1,
  "isRoot": true,
  "tools": {{
    "fable": {{ "version": "%s{options.FableVersion}", "commands": [ "fable" ], "rollForward": false }}
  }}
}}
"""

    let packageJson (options: SolidExamplesOptions) =
        $"""{{
  "name": "partas-solid-docs",
  "private": true,
  "type": "module",
  "dependencies": {{
    "@solidjs/compiler": "%s{options.SolidVersion}",
    "@solidjs/web": "%s{options.SolidVersion}",
    "solid-js": "%s{options.SolidVersion}",
    "rolldown": "%s{options.RolldownVersion}"
  }},
  "overrides": {{
    "solid-js": "%s{options.SolidVersion}",
    "@solidjs/web": "%s{options.SolidVersion}"
  }}
}}
"""

    /// <summary>Run a tool to completion, keeping everything it printed.</summary>
    let run (timeout: TimeSpan) (directory: string) (file: string) (arguments: string list) =
        // npm is a batch file on Windows, which only the shell can start.
        let file, arguments =
            if OperatingSystem.IsWindows() && (file = "npm" || file = "npx") then
                "cmd.exe", "/d" :: "/s" :: "/c" :: file :: arguments
            else
                file, arguments

        let info = ProcessStartInfo(file, arguments)
        info.WorkingDirectory <- directory
        info.RedirectStandardOutput <- true
        info.RedirectStandardError <- true
        info.UseShellExecute <- false
        info.StandardOutputEncoding <- Encoding.UTF8
        info.StandardErrorEncoding <- Encoding.UTF8
        // Fable prints its banner and colours unless told it is not talking to a person.
        info.Environment["DOTNET_CLI_TELEMETRY_OPTOUT"] <- "1"
        info.Environment["NO_COLOR"] <- "1"

        let output = StringBuilder()
        let gate = obj ()

        let collect (args: DataReceivedEventArgs) =
            if not (isNull args.Data) then
                lock gate (fun () -> output.AppendLine args.Data |> ignore)

        use proc = new Process(StartInfo = info)
        proc.OutputDataReceived.Add collect
        proc.ErrorDataReceived.Add collect
        proc.Start() |> ignore
        proc.BeginOutputReadLine()
        proc.BeginErrorReadLine()

        if proc.WaitForExit(timeout) then
            proc.WaitForExit()

            {
                ExitCode = proc.ExitCode
                Output = lock gate output.ToString
                TimedOut = false
            }
        else
            try
                proc.Kill true
            with _ ->
                ()

            {
                ExitCode = -1
                Output = lock gate output.ToString
                TimedOut = true
            }
